In [1]:
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import optimizers
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

In [2]:
# MNIST 데이터셋 불러오기
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [4]:
# 60000, 가로, 세로, 필터
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28, 1) (60000,)
(10000, 28, 28, 1) (10000,)


In [5]:
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [6]:
input_shape = (28, 28, 1)     # 행, 열, 채널
model = Sequential()
model.add(Conv2D(32, kernel_size=(5, 5), padding='same',input_shape = input_shape, activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (5, 5), padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 32)        832       
                                                                 
 max_pooling2d (MaxPooling2  (None, 14, 14, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 14, 14, 64)        51264     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 7, 7, 64)          0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 3136)              0         
                                                                 
 dense (Dense)               (None, 1000)              3

In [7]:
model.compile(loss = 'categorical_crossentropy', optimizer = optimizers.SGD(0.001), metrics=['accuracy'])
early_stopping = EarlyStopping(monitor = 'val_loss', min_delta = 0, patience = 3)

In [8]:
# fit() 메서드로 모델 훈련 시키기
hist = model.fit(
    x_train, y_train,
    epochs = 20, batch_size = 128,
    validation_data=(x_test, y_test),
    callbacks = early_stopping
    )

Epoch 1/20
469/469 [==============================] - 204s 425ms/step - loss: 0.5923 - accuracy: 0.9000 - val_loss: 0.1546 - val_accuracy: 0.9509
Epoch 2/20
469/469 [==============================] - 189s 403ms/step - loss: 0.1105 - accuracy: 0.9662 - val_loss: 0.0932 - val_accuracy: 0.9711
Epoch 3/20
469/469 [==============================] - 189s 402ms/step - loss: 0.0787 - accuracy: 0.9757 - val_loss: 0.0766 - val_accuracy: 0.9754
Epoch 4/20
469/469 [==============================] - 197s 420ms/step - loss: 0.0614 - accuracy: 0.9812 - val_loss: 0.0693 - val_accuracy: 0.9786
Epoch 5/20
469/469 [==============================] - 190s 405ms/step - loss: 0.0508 - accuracy: 0.9847 - val_loss: 0.0610 - val_accuracy: 0.9811
Epoch 6/20
469/469 [==============================] - 188s 401ms/step - loss: 0.0431 - accuracy: 0.9869 - val_loss: 0.0594 - val_accuracy: 0.9814
Epoch 7/20
469/469 [==============================] - 189s 403ms/step - loss: 0.0372 - accuracy: 0.9887 - val_loss: 0.0536 -

In [9]:
# 테스트 데이터로 정확도 측정하기
test_loss, test_acc = model.evaluate(x_test, y_test)
print('test_acc: ', test_acc)

313/313 [==============================] - 10s 33ms/step - loss: 0.0453 - accuracy: 0.9864
test_acc:  0.9864000082015991


In [10]:
predit = model.predict(x_test)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(y_test[0 :5])

313/313 [==============================] - 9s 28ms/step
[[2.21240208e-13 2.77541987e-12 6.05498851e-09 9.19658476e-07
  8.81199280e-12 3.58909213e-12 7.97580342e-20 9.99998987e-01
  1.35098597e-13 1.86871296e-09]
 [1.96411082e-10 2.78505894e-07 9.99999702e-01 3.85749028e-12
  3.81669785e-15 2.54786584e-16 1.38198186e-11 4.54353767e-15
  8.33593871e-12 4.62046054e-15]
 [4.35618233e-07 9.99900877e-01 5.62426249e-06 2.96754212e-08
  6.03031094e-06 1.21758879e-08 6.65893580e-08 8.49753123e-05
  1.50380993e-06 4.31873048e-07]
 [9.99996603e-01 2.46669768e-11 6.73731204e-09 9.52211365e-11
  4.10201817e-10 3.56790975e-09 3.30023568e-06 3.98454846e-11
  1.91603178e-10 9.46230094e-10]
 [1.62560368e-10 2.84328010e-08 5.67345948e-10 1.81917342e-10
  9.99891818e-01 1.11732341e-07 8.49659898e-08 2.77996378e-07
  5.12910325e-10 1.07527558e-04]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 