In [ ]:
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import optimizers
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

In [ ]:
# MNIST 데이터셋 불러오기
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [ ]:
# 60000, 가로, 세로, 필터
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(60000, 28, 28, 1) (60000,)
(10000, 28, 28, 1) (10000,)


In [ ]:
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [ ]:
input_shape = (28, 28, 1)     # 행, 열, 채널
from keras.layers import BatchNormalization
model = Sequential()

model.add(Conv2D(32, kernel_size=(5, 5), padding='same',
         input_shape = input_shape, activation='relu', kernel_initializer='he_normal'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())

model.add(Conv2D(64, (5, 5), padding='same', activation='relu', kernel_initializer='he_normal'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 32)        832       
                                                                 
 max_pooling2d (MaxPooling2  (None, 14, 14, 32)        0         
 D)                                                              
                                                                 
 batch_normalization (Batch  (None, 14, 14, 32)        128       
 Normalization)                                                  
                                                                 
 conv2d_1 (Conv2D)           (None, 14, 14, 64)        51264     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 7, 7, 64)          0         
 g2D)                                                            
                                                        

In [ ]:
# 모델 컴파일 하기
model_checkpoint = ModelCheckpoint(filepath =  "./model.h5", monitor='val_loss', verbose=1, save_best_only=True)
early_stopping = EarlyStopping(monitor = 'val_loss', min_delta = 0, patience = 3)

# 모델 학습과정 설정하기
model.compile(loss = 'categorical_crossentropy', optimizer = optimizers.Adam(lr = 0.001), metrics=['accuracy'])

In [ ]:
# fit() 메서드로 모델 훈련 시키기
hist = model.fit(
    x_train, y_train,
    epochs = 20, batch_size = 128,
    validation_data=(x_test, y_test),
    callbacks = [model_checkpoint, early_stopping]
    )

Epoch 1/20
469/469 [==============================] - ETA: 0s - loss: 0.2068 - accuracy: 0.9443
Epoch 1: val_loss improved from inf to 0.05325, saving model to ./model.h5
469/469 [==============================] - 116s 236ms/step - loss: 0.2068 - accuracy: 0.9443 - val_loss: 0.0533 - val_accuracy: 0.9830
Epoch 2/20


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


469/469 [==============================] - ETA: 0s - loss: 0.0831 - accuracy: 0.9761
Epoch 2: val_loss improved from 0.05325 to 0.04097, saving model to ./model.h5
469/469 [==============================] - 113s 240ms/step - loss: 0.0831 - accuracy: 0.9761 - val_loss: 0.0410 - val_accuracy: 0.9873
Epoch 3/20
469/469 [==============================] - ETA: 0s - loss: 0.0663 - accuracy: 0.9807
Epoch 3: val_loss improved from 0.04097 to 0.03347, saving model to ./model.h5
469/469 [==============================] - 111s 236ms/step - loss: 0.0663 - accuracy: 0.9807 - val_loss: 0.0335 - val_accuracy: 0.9898
Epoch 4/20
469/469 [==============================] - ETA: 0s - loss: 0.0579 - accuracy: 0.9836
Epoch 4: val_loss improved from 0.03347 to 0.03205, saving model to ./model.h5
469/469 [==============================] - 109s 234ms/step - loss: 0.0579 - accuracy: 0.9836 - val_loss: 0.0320 - val_accuracy: 0.9896
Epoch 5/20
469/469 [==============================] - ETA: 0s - loss: 0.0468 - ac

In [ ]:
# 테스트 데이터로 정확도 측정하기
test_loss, test_acc = model.evaluate(x_test, y_test)
print('test_acc: ', test_acc)

313/313 [==============================] - 6s 20ms/step - loss: 0.0310 - accuracy: 0.9922
test_acc:  0.9922000169754028


In [ ]:
predit = model.predict(x_test)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(y_test[0 :5])

313/313 [==============================] - 5s 17ms/step
[[2.90747864e-17 1.12600094e-13 6.86217707e-16 1.87106995e-15
  3.26283841e-16 1.56006528e-17 8.24918791e-23 9.99999940e-01
  7.65687360e-20 2.91849982e-11]
 [3.60348051e-19 1.02536266e-13 9.99999940e-01 3.62965323e-18
  4.63442579e-22 3.36394666e-24 2.59940344e-19 6.49904757e-20
  3.15463886e-19 2.35879212e-24]
 [2.58383835e-11 9.99999940e-01 6.31931183e-12 1.90660056e-13
  1.73140557e-10 9.65838173e-11 2.07308198e-11 4.85445321e-12
  2.09795598e-10 6.96253888e-11]
 [9.99999940e-01 1.33023190e-10 7.04658998e-10 2.76524409e-13
  1.01567851e-10 5.11404391e-11 3.14133142e-09 2.30754171e-09
  1.13392309e-10 4.25607860e-09]
 [3.90561471e-15 1.25464168e-12 1.09840461e-11 1.28884254e-14
  9.99999940e-01 1.58111185e-14 1.68471194e-12 8.56468993e-11
  1.95217920e-13 1.48796175e-08]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 