In [1]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
import tensorflow as tf

In [2]:
# MNIST 데이터셋 불러오기
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [13]:
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


In [4]:
train_images = train_images.reshape((60000, 28 * 28))
test_images = test_images.reshape((10000, 28 * 28))
print(train_images.shape)
print(test_images.shape)

(60000, 784)
(10000, 784)


In [5]:
# 정규화
train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255
#print("train_image : ", train_images[:1])
#print("test_images : ", test_images[:1])

In [6]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print("train_labels : ", train_labels[0])
print("test_labels  : ", test_labels[0])

train_labels :  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
test_labels  :  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [20]:
# 모델 정의
model = Sequential()
model.add(Dense(512, input_shape=(28 * 28,), activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 512)               401920    
                                                                 
 dense_7 (Dense)             (None, 512)               262656    
                                                                 
 dense_8 (Dense)             (None, 10)                5130      
                                                                 
Total params: 669706 (2.55 MB)
Trainable params: 669706 (2.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
early_stopping = EarlyStopping(monitor = 'val_loss', min_delta = 0, patience = 3)
model.compile(loss = 'categorical_crossentropy', optimizer = optimizers.SGD(0.001), metrics=['accuracy'])

In [22]:
# fit() 메서드로 모델 훈련 시키기
model.fit(train_images, train_labels,
          epochs = 100, batch_size = 200,
          validation_data=(test_images, test_labels),
          callbacks = [early_stopping])

Epoch 1/100
300/300 [==============================] - 2s 4ms/step - loss: 2.2231 - accuracy: 0.2570 - val_loss: 2.1153 - val_accuracy: 0.4461
Epoch 2/100
300/300 [==============================] - 1s 5ms/step - loss: 2.0195 - accuracy: 0.5643 - val_loss: 1.9116 - val_accuracy: 0.6477
Epoch 3/100
300/300 [==============================] - 2s 5ms/step - loss: 1.8174 - accuracy: 0.6794 - val_loss: 1.7018 - val_accuracy: 0.7100
Epoch 4/100
300/300 [==============================] - 1s 4ms/step - loss: 1.6103 - accuracy: 0.7312 - val_loss: 1.4912 - val_accuracy: 0.7545
Epoch 5/100
300/300 [==============================] - 1s 4ms/step - loss: 1.4095 - accuracy: 0.7634 - val_loss: 1.2957 - val_accuracy: 0.7845
Epoch 6/100
300/300 [==============================] - 1s 3ms/step - loss: 1.2299 - accuracy: 0.7855 - val_loss: 1.1279 - val_accuracy: 0.8049
Epoch 7/100
300/300 [==============================] - 1s 4ms/step - loss: 1.0797 - accuracy: 0.8037 - val_loss: 0.9918 - val_accuracy: 0.8182

In [23]:
# 테스트 데이터로 정확도 측정하기
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('test_acc: ', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.2471 - accuracy: 0.9320
test_acc:  0.9319999814033508


In [11]:
predit = model.predict(test_images)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(test_labels[0:5])

313/313 [==============================] - 1s 2ms/step
[[8.72408345e-05 4.16307302e-07 1.30716944e-04 1.49387622e-03
  2.97629094e-06 7.63298958e-05 1.15474549e-07 9.97193396e-01
  2.81978173e-05 9.86746978e-04]
 [6.58451626e-03 1.77243084e-04 9.40131605e-01 2.80346535e-02
  1.82645849e-07 8.58328398e-03 1.42855765e-02 2.71030387e-07
  2.20196834e-03 6.93675645e-07]
 [8.75483966e-05 9.74393725e-01 6.52157143e-03 2.72105192e-03
  7.73163629e-04 2.64568347e-03 2.15065689e-03 5.02214301e-03
  4.49532457e-03 1.18917786e-03]
 [9.99108255e-01 3.58844621e-09 1.90123406e-04 2.22017134e-05
  5.85692206e-08 4.20899043e-04 1.72556014e-04 3.94482668e-05
  2.25143813e-05 2.39828933e-05]
 [5.38445718e-04 4.98044756e-05 5.49838273e-03 3.67528788e-04
  9.24748361e-01 1.26609404e-03 4.27565444e-03 5.69022354e-03
  3.72522930e-03 5.38402870e-02]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0

In [12]:
predit = model.predict(test_images)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(test_labels[0:5])

313/313 [==============================] - 1s 2ms/step
[[8.72408345e-05 4.16307302e-07 1.30716944e-04 1.49387622e-03
  2.97629094e-06 7.63298958e-05 1.15474549e-07 9.97193396e-01
  2.81978173e-05 9.86746978e-04]
 [6.58451626e-03 1.77243084e-04 9.40131605e-01 2.80346535e-02
  1.82645849e-07 8.58328398e-03 1.42855765e-02 2.71030387e-07
  2.20196834e-03 6.93675645e-07]
 [8.75483966e-05 9.74393725e-01 6.52157143e-03 2.72105192e-03
  7.73163629e-04 2.64568347e-03 2.15065689e-03 5.02214301e-03
  4.49532457e-03 1.18917786e-03]
 [9.99108255e-01 3.58844621e-09 1.90123406e-04 2.22017134e-05
  5.85692206e-08 4.20899043e-04 1.72556014e-04 3.94482668e-05
  2.25143813e-05 2.39828933e-05]
 [5.38445718e-04 4.98044756e-05 5.49838273e-03 3.67528788e-04
  9.24748361e-01 1.26609404e-03 4.27565444e-03 5.69022354e-03
  3.72522930e-03 5.38402870e-02]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0