In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np
import tensorflow as tf

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# /content/drive/MyDrive/Colab Notebooks/classifier/iris.csv
filename = '/content/drive/MyDrive/Colab Notebooks/classifier/iris.csv'
data = pd.read_csv(filename)
print(data.info())
print(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [4]:
# 중복을 허용하지 않고 있는 데이터의 모든 종류를 출력
print("품종 종류:", data["variety"].unique(), sep="\n")

# 라벨을 정수로 인덱싱
data['variety'] = data['variety'].replace(['Virginica','Setosa','Versicolor'],[0,1,2])
print("품종 종류:", data["variety"].unique(), sep="\n")

품종 종류:
['Setosa' 'Versicolor' 'Virginica']
품종 종류:
[1 2 0]


In [5]:
data_X = data[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values
data_y = data['variety'].values
print(data_X[:5])
print(data_y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[1 1 1 1 1]


In [6]:
(train_X, test_X, train_Y, test_Y) = train_test_split(data_X, data_y, train_size=0.8)
print(train_X.shape)
print(train_Y.shape)
print(test_X.shape)
print(test_Y.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [7]:
from keras.utils import to_categorical     # 훈련 데이터와 테스트 데이터에 대해서 원-핫 인코딩
train_Y = to_categorical(train_Y)
test_Y = to_categorical(test_Y)

print(train_Y[:5])
print(test_Y[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
model= Sequential()
model.add(Dense(3, input_dim=4, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.compile(optimizer = optimizers.SGD(0.01), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(train_X, train_Y, batch_size = 1, epochs = 200, validation_data=(test_X, test_Y))

Epoch 1/200
120/120 [==============================] - 1s 4ms/step - loss: 1.5326 - accuracy: 0.2167 - val_loss: 0.8444 - val_accuracy: 0.6000
Epoch 2/200
120/120 [==============================] - 0s 2ms/step - loss: 0.7532 - accuracy: 0.7083 - val_loss: 0.6852 - val_accuracy: 0.5000
Epoch 3/200
120/120 [==============================] - 0s 2ms/step - loss: 0.6256 - accuracy: 0.7167 - val_loss: 0.5035 - val_accuracy: 0.8667
Epoch 4/200
120/120 [==============================] - 0s 2ms/step - loss: 0.5305 - accuracy: 0.7667 - val_loss: 0.4363 - val_accuracy: 0.8667
Epoch 5/200
120/120 [==============================] - 0s 2ms/step - loss: 0.5027 - accuracy: 0.7417 - val_loss: 0.4550 - val_accuracy: 0.9333
Epoch 6/200
120/120 [==============================] - 0s 2ms/step - loss: 0.4500 - accuracy: 0.7833 - val_loss: 0.8107 - val_accuracy: 0.4667
Epoch 7/200
120/120 [==============================] - 0s 2ms/step - loss: 0.4230 - accuracy: 0.8000 - val_loss: 0.8809 - val_accuracy: 0.4667

In [ ]:
model.evaluate(test_X, test_Y)

In [ ]:
predit = model.predict(test_X)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(test_Y[0:5])

In [ ]:
import matplotlib.pyplot as plt
epochs = range(1, len(history.history['accuracy']) + 1)
plt.plot(epochs, history.history['accuracy'])
plt.plot(epochs, history.history['val_accuracy'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()


In [ ]:
print("\n 테스트 정확도: %.4f" % (model.evaluate(test_X, test_Y)[1]))