In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np
from sklearn.metrics import mean_squared_error    # 오차

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
filename = '/content/drive/MyDrive/Colab Notebooks/Linear/score.csv'
data = np.loadtxt(filename, delimiter=',', dtype=np.float32)

X_data = data[ : , 0 : -1]   # slicing
Y_data = data[ : , [-1]]

In [16]:
print(X_data, "\nX_data shape:", X_data.shape)  # x_data shape: (25, 3)
print(Y_data, "\nY_data shape:", Y_data.shape)  # y_data shape: (25, 1)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
X_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
Y_data shape: (25, 1)


In [17]:
train_X = data[0 : 20, 0:-1]
train_Y = data[0 : 20, [-1]]

test_X = data[20 : , 0:-1]
test_Y = data[20 : , [-1]]

In [18]:
print(train_X, "\ntrain_X shape:", train_X.shape)  # train_X shape: (20, 3)
print(train_Y, "\ntrain_Y shape:", train_Y.shape)  # train_Y shape: (20, 1)

print(test_X, "\ntest_X shape:", test_X.shape)  # test_X shape: (5, 3)
print(test_Y, "\ntest_Y shape:", test_Y.shape)  # test_Y shape: (5, 1)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]] 
train_X shape: (20, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]] 
train_Y shape: (20, 1)
[[82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
test_X shape: (5, 3)
[[177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
test_Y shape: (5, 1)


In [19]:
# 모델 설계
model=Sequential()
model.add(Dense(1, input_dim = 3, activation = 'linear'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 4 (16.00 Byte)
Trainable params: 4 (16.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
# 학습률 : 0.01 / sgd는 경사 하강법 / Cost function : 평균제곱오차 사용.
model.compile(optimizer = optimizers.SGD(lr = 0.000001), loss='mse')  # metrics = [‘accuracy’]

hist = model.fit(train_X, train_Y, batch_size =1, epochs = 100, validation_data=(test_X, test_Y))

Epoch 1/100
20/20 [==============================] - 0s 9ms/step - loss: nan - val_loss: nan
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: nan - val_loss: nan
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: nan - val_loss: nan
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: nan - val_loss: nan
Epoch 5/100
20/20 [==============================] - 0s 3ms/step - loss: nan - val_loss: nan
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: nan - val_loss: nan
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: nan - val_loss: nan
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: nan - val_loss: nan
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: nan - val_loss: nan
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: nan - val_loss: nan
Epoch 11/100
20/20 [==============================] - 0s 4ms/step - l

In [21]:
# 모델 평가 / 모델 검증
model.evaluate(test_X, test_Y)
print(model.predict([[78.,  83.,  77.]]))
predict = model.predict(test_X)
RMSE = mean_squared_error(test_Y, predict)**0.5
print("RMSE:", RMSE)

1/1 [==============================] - 0s 191ms/step
[[nan]]
1/1 [==============================] - 0s 98ms/step


ValueError: Input contains NaN.

In [ ]:
import matplotlib.pyplot as plt
plt.plot(hist.history['loss'], 'r', label =  'loss')
plt.plot(hist.history['val_loss'], 'b', label =  'val_loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(loc='upper left')
plt.show()