In [17]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN, LSTM

In [18]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(3, 5)))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_9 (SimpleRNN)    (None, 3)                 27        
                                                                 
Total params: 27 (108.00 Byte)
Trainable params: 27 (108.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model = Sequential()
model.add(SimpleRNN(5, input_shape=(3, 10)))
model.add(Dense(1, activation='linear'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_10 (SimpleRNN)   (None, 5)                 80        
                                                                 
 dense_2 (Dense)             (None, 1)                 6         
                                                                 
Total params: 86 (344.00 Byte)
Trainable params: 86 (344.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model = Sequential()
model.add(LSTM(3, input_shape=(3, 5)))

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 3)                 108       
                                                                 
Total params: 108 (432.00 Byte)
Trainable params: 108 (432.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model = Sequential()
model.add(LSTM(5, input_shape=(3, 10)))
model.add(Dense(1, activation='linear'))
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 5)                 320       
                                                                 
 dense_3 (Dense)             (None, 1)                 6         
                                                                 
Total params: 326 (1.27 KB)
Trainable params: 326 (1.27 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## **SimpleRNN** 인자
return_sequences
return_state

In [22]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8],
           [1.0, 3.1, 2.5, 0.7, 1.1],
           [0.3, 2.1, 1.5, 2.1, 0.1],
           [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [23]:
train_X=[[[0.1, 4.2, 1.5, 1.1, 2.8],
          [1.0, 3.1, 2.5, 0.7, 1.1],
          [0.3, 2.1, 1.5, 2.1, 0.1],
          [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(np.shape(train_X))  # 1, 4, 5

(1, 4, 5)


In [24]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(4, 5), return_state=False))
model.summary()

hidden_states=model(train_X)
print(hidden_states)

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_11 (SimpleRNN)   (None, 3)                 27        
                                                                 
Total params: 27 (108.00 Byte)
Trainable params: 27 (108.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
tf.Tensor([[ 0.9696719   0.82990503 -0.8978929 ]], shape=(1, 3), dtype=float32)


In [25]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(4, 5), return_state=False))

hidden_states = model(train_X)
print(hidden_states)

tf.Tensor([[ 0.97373873 -0.9783642  -0.9981562 ]], shape=(1, 3), dtype=float32)


In [28]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(4, 5), return_sequences=True))
hidden_states = model(train_X)
print(hidden_states)

tf.Tensor(
[[[-0.95612156 -0.9079012  -0.9920391 ]
  [-0.6811384  -0.96933156 -0.9906188 ]
  [-0.9788833  -0.9127111  -0.9762496 ]
  [ 0.51882803 -0.9973904  -0.9806287 ]]], shape=(1, 4, 3), dtype=float32)


In [29]:
model = Sequential()
model.add(LSTM(3, input_shape=(4, 5), return_state=False))

hidden_states = model(train_X)
print(hidden_states)

tf.Tensor([[-0.03920788 -0.61658734  0.23188713]], shape=(1, 3), dtype=float32)


In [30]:
model = Sequential()
model.add(LSTM(3, input_shape=(4, 5), return_sequences=True))
hidden_states = model(train_X)
print(hidden_states)

tf.Tensor(
[[[-0.37103498 -0.19349168  0.00275358]
  [-0.3788534  -0.20271607  0.02958148]
  [-0.26545906 -0.11012091  0.17446809]
  [-0.46279708 -0.18867202  0.22168857]]], shape=(1, 4, 3), dtype=float32)
