In [ ]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
import tensorflow as tf

In [ ]:
# MNIST 데이터셋 불러오기
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [ ]:
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)


In [ ]:
train_images = train_images.reshape((60000, 28 * 28))
test_images = test_images.reshape((10000, 28 * 28))
print(train_images.shape)
print(test_images.shape)

(60000, 784)
(10000, 784)


In [ ]:
# 정규화
train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255
#print("train_image : ", train_images[:1])
#print("test_images : ", test_images[:1])

In [ ]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
print("train_labels : ", train_labels[0])
print("test_labels  : ", test_labels[0])

train_labels :  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
test_labels  :  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [ ]:
# 모델 정의
model = Sequential()
model.add(Dense(512, input_shape=(28 * 28,), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_1 (Dense)             (None, 512)               262656    
                                                                 
 dropout_1 (Dropout)         (None, 512)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                5130      
                                                                 
Total params: 669706 (2.55 MB)
Trainable params: 669706 (2.55 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# 모델 컴파일 하기
model_checkpoint = ModelCheckpoint(filepath =  "./model.h5", monitor='val_loss', verbose=1, save_best_only=True)
early_stopping = EarlyStopping(monitor = 'val_loss', min_delta = 0, patience = 3)

# 모델 학습과정 설정하기
model.compile(loss = 'categorical_crossentropy', optimizer = optimizers.SGD(0.001), metrics=['accuracy'])

In [ ]:
# fit() 메서드로 모델 훈련 시키기
model.fit(train_images, train_labels,
          epochs = 100, batch_size = 200,
          validation_data=(test_images, test_labels),
          callbacks = [model_checkpoint, early_stopping])

Epoch 1/100
299/300 [============================>.] - ETA: 0s - loss: 1.6962 - accuracy: 0.4646
Epoch 1: val_loss improved from inf to 0.90343, saving model to ./model.h5
300/300 [==============================] - 9s 12ms/step - loss: 1.6944 - accuracy: 0.4652 - val_loss: 0.9034 - val_accuracy: 0.8094
Epoch 2/100
 11/300 [>.............................] - ETA: 1s - loss: 1.1819 - accuracy: 0.6386

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


295/300 [============================>.] - ETA: 0s - loss: 0.9290 - accuracy: 0.7182
Epoch 2: val_loss improved from 0.90343 to 0.53795, saving model to ./model.h5
300/300 [==============================] - 2s 8ms/step - loss: 0.9271 - accuracy: 0.7187 - val_loss: 0.5380 - val_accuracy: 0.8615
Epoch 3/100
295/300 [============================>.] - ETA: 0s - loss: 0.6964 - accuracy: 0.7857
Epoch 3: val_loss improved from 0.53795 to 0.42979, saving model to ./model.h5
300/300 [==============================] - 2s 8ms/step - loss: 0.6955 - accuracy: 0.7859 - val_loss: 0.4298 - val_accuracy: 0.8828
Epoch 4/100
295/300 [============================>.] - ETA: 0s - loss: 0.5880 - accuracy: 0.8202
Epoch 4: val_loss improved from 0.42979 to 0.37567, saving model to ./model.h5
300/300 [==============================] - 2s 7ms/step - loss: 0.5878 - accuracy: 0.8203 - val_loss: 0.3757 - val_accuracy: 0.8949
Epoch 5/100
297/300 [============================>.] - ETA: 0s - loss: 0.5284 - accuracy: 0

In [ ]:
# 테스트 데이터로 정확도 측정하기
test_loss, test_acc = model.evaluate(test_images, test_labels)
print('test_acc: ', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0824 - accuracy: 0.9747
test_acc:  0.9746999740600586


In [ ]:
predit = model.predict(test_images)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(test_labels[0:5])

313/313 [==============================] - 1s 2ms/step
[[9.3684207e-07 9.1843725e-07 3.4951787e-05 4.6737983e-05 2.9040965e-08
  1.0731230e-06 8.3030122e-10 9.9990511e-01 1.0356973e-07 1.0100840e-05]
 [7.6065280e-06 1.5824151e-05 9.9944800e-01 4.9510144e-04 2.9183946e-09
  3.7566413e-06 2.1314323e-05 4.4209372e-08 8.1735743e-06 5.5309690e-10]
 [2.2616721e-06 9.9869871e-01 3.3990401e-04 2.7996550e-05 9.4403338e-05
  1.9955045e-05 6.9573340e-05 5.9050921e-04 1.5168112e-04 4.9881432e-06]
 [9.9940920e-01 3.0830738e-06 5.0409493e-05 1.9567833e-06 1.6285430e-05
  2.1151103e-05 3.6232997e-04 9.6854601e-05 1.5279858e-06 3.7187285e-05]
 [1.3109588e-05 1.0067366e-05 4.2284984e-05 2.3635062e-06 9.9394810e-01
  1.7821354e-05 5.2811392e-05 3.3843913e-04 1.0494834e-05 5.5646109e-03]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
predit = model.predict(test_images)
#for i in range(0,len(predit)) :
#    print("예측값 : ", predit[i], "\t실제값 : ", test_Y[i])
print(predit[0:5])
print(test_labels[0:5])

313/313 [==============================] - 0s 1ms/step
[[9.3684207e-07 9.1843725e-07 3.4951787e-05 4.6737983e-05 2.9040965e-08
  1.0731230e-06 8.3030122e-10 9.9990511e-01 1.0356973e-07 1.0100840e-05]
 [7.6065280e-06 1.5824151e-05 9.9944800e-01 4.9510144e-04 2.9183946e-09
  3.7566413e-06 2.1314323e-05 4.4209372e-08 8.1735743e-06 5.5309690e-10]
 [2.2616721e-06 9.9869871e-01 3.3990401e-04 2.7996550e-05 9.4403338e-05
  1.9955045e-05 6.9573340e-05 5.9050921e-04 1.5168112e-04 4.9881432e-06]
 [9.9940920e-01 3.0830738e-06 5.0409493e-05 1.9567833e-06 1.6285430e-05
  2.1151103e-05 3.6232997e-04 9.6854601e-05 1.5279858e-06 3.7187285e-05]
 [1.3109588e-05 1.0067366e-05 4.2284984e-05 2.3635062e-06 9.9394810e-01
  1.7821354e-05 5.2811392e-05 3.3843913e-04 1.0494834e-05 5.5646109e-03]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
